
#pragma once

enum RESULT_CODE : u32
{
	RESULT_CODE_SUCCESS,
	RESULT_CODE_FAILED_MEMORY_ARENA_INITIALISATION,
	RESULT_CODE_UNKNOWN_OPTIONAL_COMMAND,
	RESULT_CODE_NO_INPUT_FILES,
	RESULT_CODE_FAILED_TO_OPEN_INPUT_FILE,
	RESULT_CODE_INPUT_FILE_SIZES_DONT_MATCH,
	RESULT_CODE_FAILED_TO_ALLOCATE_MEMORY_FOR_OUTPUT_IMAGE,
	RESULT_CODE_FAILED_TO_CREATE_OUTPUT_FILE,
};

static inline const char *error_code_string( RESULT_CODE code )
{
	switch ( code )
	{
	case RESULT_CODE_SUCCESS: return "RESULT_CODE_SUCCESS";
	case RESULT_CODE_FAILED_MEMORY_ARENA_INITIALISATION: return "RESULT_CODE_FAILED_MEMORY_ARENA_INITIALISATION";
	case RESULT_CODE_UNKNOWN_OPTIONAL_COMMAND: return "RESULT_CODE_UNKNOWN_OPTIONAL_COMMAND";
	case RESULT_CODE_NO_INPUT_FILES: return "RESULT_CODE_NO_INPUT_FILES";
	case RESULT_CODE_FAILED_TO_OPEN_INPUT_FILE: return "RESULT_CODE_FAILED_TO_OPEN_INPUT_FILE";
	case RESULT_CODE_INPUT_FILE_SIZES_DONT_MATCH: return "RESULT_CODE_INPUT_FILE_SIZES_DONT_MATCH";
	case RESULT_CODE_FAILED_TO_ALLOCATE_MEMORY_FOR_OUTPUT_IMAGE: return "RESULT_CODE_FAILED_TO_ALLOCATE_MEMORY_FOR_OUTPUT_IMAGE";
	case RESULT_CODE_FAILED_TO_CREATE_OUTPUT_FILE: return "RESULT_CODE_FAILED_TO_CREATE_OUTPUT_FILE";
	}

	return "UNKNOWN ERROR CODE";
}